- name: generate the SSH key pair for connecting ansible master to slaves
  shell: ssh-keygen -N '' -f /home/ec2-user/.ssh/id_ansible_slave

- name: import the key material into EC2
  ec2_key:
    name: id_ansible_slave
    key_material: "{{ item }}"
  with_file: /home/ec2-user/.ssh/id_ansible_slave.pub
